<?php
    $view = $this;
    $params = $this->params;

    $sqSolicitacao = function($row) use ($view, $params) {
        return $row['sqSolicitacao'];
    };

    $dsSolicitacao = function($row) use ($view, $params) {
        $dsSolicitacao = $row['dsSolicitacao'];
        $dsSolicitacao = "<div width='150px' class='wrapword'>{$dsSolicitacao}</div>";
        return $dsSolicitacao;
    };

    $dtSolicitacao = function($row) use ($view, $params) {
        $dtSolicitacao = new \Zend_Date($row['dtSolicitacao']);
        return $dtSolicitacao->get(\Zend_Date::DATETIME_MEDIUM);
    };

    $acao = function($row) use ($view, $params) {
        $arrBtn   = array(
            'detalhar' => $view->actionButton('Detalhar Demanda', 'Solicitacao.acoes.visualizar', array($row['sqSolicitacao']), 'list-alt')
        );
        
        return $view->buttonGroup(join(' ', $arrBtn), count($arrBtn));
    };

    $configArray = array('columns' => array( 0 => array( 'column' => $sqSolicitacao),
                                             1 => array( 'column' => $dtSolicitacao),
                                             2 => array( 'column' => 'noTipoStatusSolicitacao'),
                                             3 => array( 'column' => 'noPessoaAbertura'),
                                             4 => array( 'column' => 'noUnidadeAbertura'),
                                             5 => array( 'column' => 'nuArtefato'),
                                             6 => array( 'column' => 'noTipoAssuntoSolicitacao'),
                                             7 => array( 'column' => $dsSolicitacao),
                                             8 => array( 'column' => $acao)
    ));


    $parse = new \Core_Grid_Parse($configArray);
    $this->result['sEcho'] = $this->params['sEcho'];
    $data  = $parse->parse($this->result);

    echo json_encode($data);