<?php
/*
 * Copyright 2011 ICMBio
 * Este arquivo é parte do programa SISICMBio
 * O SISICMBio é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro dos termos
 * da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão
 * 2 da Licença.
 *
 * Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem
 * uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
 * Licença Pública Geral GNU/GPL em português para maiores detalhes.
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENCA.txt",
 * junto com este programa, se não, acesse o Portal do Software Público Brasileiro no endereço
 * www.softwarepublico.gov.br ou escreva para a Fundação do Software Livre(FSF)
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA
 * */
namespace br\gov\mainapp\application\libcorp\tipoVinculo\valueObject;
use br\gov\sial\core\valueObject\ValueObjectAbstract as ParentValueObject,
    br\gov\mainapp\application\libcorp\tipoVinculo\mvcb\business\TipoVinculoBusiness;

/**
  * SISICMBio
  *
  * Generated By SIAL Generator - vs 0.2.0
  *
  * @name TipoVinculoValueObject
  * @package br.gov.icmbio.sisicmbio.application.libcorp.tipoVinculo
  * @subpackage valueObject
  * @schema(name="corporativo")
  * @entity(name="tipo_vinculo")
  * @author Fabio Lima <fabioolima@gmail.com>
  * @author J. Augusto <augustowebd@gmail.com>
  * @version $Id$
  * @log(name="all")
  * */
class TipoVinculoValueObject extends ParentValueObject
{
    /**
     * @attr (
     *  name="noTipoVinculo",
     *  database="no_tipo_vinculo",
     *  type="string",
     *  nullable="FALSE",
     *  get="getNoTipoVinculo",
     *  set="setNoTipoVinculo"
     * )
     * */
     private $_noTipoVinculo;

    /**
     * @attr (
     *  name="sqTipoVinculo",
     *  database="sq_tipo_vinculo",
     *  primaryKey="TRUE",
     *  type="integer",
     *  nullable="FALSE",
     *  get="getSqTipoVinculo",
     *  set="setSqTipoVinculo"
     * )
     * */
     private $_sqTipoVinculo;

    /**
     * @attr (
     *  name="sqTipoVinculoPai",
     *  database="sq_tipo_vinculo_pai",
     *  type="integer",
     *  get="getSqTipoVinculoPai",
     *  set="setSqTipoVinculoPai"
     * )
     * */
     private $_sqTipoVinculoPai;

    /**
     * @param string $noTipoVinculo
     * @param integer $sqTipoVinculo
     * */
    public function __construct ($noTipoVinculo = NULL,
                                 $sqTipoVinculo = NULL,
                                 $sqTipoVinculoPai = NULL)
    {
        parent::__construct();
        $this->setNoTipoVinculo($noTipoVinculo)
             ->setSqTipoVinculo($sqTipoVinculo)
             ->setSqTipoVinculoPai($sqTipoVinculoPai)
             ;
    }

    /**
     * @return string
     * */
    public function getNoTipoVinculo ()
    {
        return $this->_noTipoVinculo;
    }

    /**
     * @return integer
     * */
    public function getSqTipoVinculo ()
    {
        return $this->_sqTipoVinculo;
    }

    /**
     * @param string $noTipoVinculo
     * @return br\gov\mainapp\application\libcorp\tipoVinculo\valueObject\TipoVinculoValueObject
     * */
    public function setNoTipoVinculo ($noTipoVinculo = NULL)
    {
        $this->_noTipoVinculo = $noTipoVinculo;
        return $this;
    }

    /**
     * @param integer $sqTipoVinculo
     * @return br\gov\mainapp\application\libcorp\tipoVinculo\valueObject\TipoVinculoValueObject
     * */
    public function setSqTipoVinculo ($sqTipoVinculo = NULL)
    {
        $this->_sqTipoVinculo = $sqTipoVinculo;
        return $this;
    }

    /**
     * @param integer $sqTipoVinculoPai
     * @return TipoVinculoValueObject
     * */
    public function setSqTipoVinculoPai ($sqTipoVinculoPai = NULL)
    {
        $this->_sqTipoVinculoPai = $sqTipoVinculoPai;
        return $this;
    }
    
    /**
     * @return TipoVinculoValueObject
     * */
    public function getSqTipoVinculoPai ()
    {
        if ((NULL != $this->_sqTipoVinculoPai) && !($this->_sqTipoVinculoPai instanceof parent)) {
            $this->_sqTipoVinculoPai = TipoVinculoBusiness::factory(NULL, 'libcorp')->find($this->_sqTipoVinculoPai);
        }
        return $this->_sqTipoVinculoPai;
    }    
}