<?php

$view = $this;

$acao = function($row) use ($view) {

    $arrSqArtefato = array('sqArtefato' => $row['sqArtefato']);

    $arrBtn = array();

    $menuCorrigir = $view->actionButton('Corrigir', 'Artefato.migrar', $arrSqArtefato, 'wrench');

    $arrBtn[] =  $menuCorrigir;
    
    return $view->buttonGroup(join(' ', $arrBtn), 1);
};

$nuArtefato = function($row) use($view) {
    return ($row['nuArtefato']) ?
                ($row['coAmbitoProcesso'] == 'F') ?
                    $view->maskNumber($row['nuArtefato'], '99999.999999/9999-99') : $row['nuArtefato'] : '';
};


if ($this->dto->sqTipoArtefato == \Core_Configuration::getSgdoceTipoArtefatoProcesso()) {
    $configArray = array(
        'columns' => array(
            array('column' => 'nuArtefato'),
            array('column' => $acao)
        )
    );
} else {
    $configArray = array(
        'columns' => array(
            array('column' => function($row) {
            return ($row['nuDigital']) ? $row['nuDigital'] : '';
        }),
            array('column' => 'nuArtefato'),
            array('column' => $acao)
        )
    );
}

$this->grid->setConfig($configArray);
$data = $this->grid->parseData($this->result);

echo json_encode($data);
