<div class="tab-pane active" id="dadosValidacao">
	<fieldset>
		<br>
        <div class="control-group">
          <label class="control-label" for="nuDigital">
			<span class="required" title="Required field">*</span> Digital
		</label>
          <div class="controls">
			<div class="input-append">
				<input type="text" class="input-large" name="nuDigital" id="digital">
				<a class="btn right" title="Validar"><i class="icon-ok"></i></a>
			</div>
          </div>
        </div>
	</fieldset>
	<br>
</div>
