<?php

$view = $this;

$acao = function($row) use ($view) {
    return $view->actionButton('Excluir', 'AnexoSic.delete', array($row['sqAnexoSic']), 'trash');
};

$dtCadastro = function($row) {
    return $row['dtCadastro']->toString('dd/MM/YYYY');
};

$configArray = array('columns' => array(
        array('column' => 'noArquivoReal'),
        array('column' => $dtCadastro),
        array('column' => $acao)
        ));

$this->grid->setConfig($configArray);
$data = $this->grid->parseData($this->result);

echo json_encode($data);
