<?php
/*
 * Copyright 2011 ICMBio
 * Este arquivo é parte do programa SISICMBio
 * O SISICMBio é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro dos termos
 * da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão
 * 2 da Licença.
 *
 * Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem
 * uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
 * Licença Pública Geral GNU/GPL em português para maiores detalhes.
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENCA.txt",
 * junto com este programa, se não, acesse o Portal do Software Público Brasileiro no endereço
 * www.softwarepublico.gov.br ou escreva para a Fundação do Software Livre(FSF)
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA
 * */
namespace br\gov\mainapp\application\libcorp\tipoVinculoSistemico\valueObject;
use br\gov\sial\core\valueObject\ValueObjectAbstract as ParentValueObject;

/**
  * SISICMBio
  *
  * Generated By SIAL Generator - vs 0.2.0
  *
  * @name TipoVinculoSistemicoValueObject
  * @package br.gov.icmbio.sisicmbio.application.libcorp.tipoVinculo
  * @subpackage valueObject
  * @schema(name="corporativo")
  * @entity(name="tipo_vinculo_sistemico")
  * @author Fabio Lima <fabioolima@gmail.com>
  * @author J. Augusto <augustowebd@gmail.com>
  * @version $Id$
  * */
class TipoVinculoSistemicoValueObject extends ParentValueObject
{
    /**
     * @attr (
     *  name="noTipoVinculoSistemico",
     *  database="no_tipo_vinculo_sistemico",
     *  type="string",
     *  nullable="FALSE",
     *  get="getNoTipoVinculoSistemico",
     *  set="setNoTipoVinculoSistemico"
     * )
     * */
     private $_noTipoVinculoSistemico;

    /**
     * @attr (
     *  name="sqTipoVinculoSistemico",
     *  database="sq_tipo_vinculo_sistemico",
     *  primaryKey="TRUE",
     *  type="integer",
     *  nullable="FALSE",
     *  get="getSqTipoVinculoSistemico",
     *  set="setSqTipoVinculoSistemico"
     * )
     * */
     private $_sqTipoVinculoSistemico;

     /**
     * @attr (
     *  name="sqSistema",
     *  database="sq_sistema",
     *  type="integer",
     *  nullable="TRUE",
     *  get="getSqSistema",
     *  set="setSqSistema"
     * )
     * */
     private $_sqSistema;

    /**
     * @param string $noTipoVinculoSistemico
     * @param integer $sqTipoVinculoSistemico
     * @param integer $sqSistema
     * */
    public function __construct ($noTipoVinculoSistemico = NULL,
                                 $sqTipoVinculoSistemico = NULL,
                                 $sqSistema = NULL)
    {
        parent::__construct();
        $this->setNoTipoVinculoSistemico($noTipoVinculoSistemico)
             ->setSqTipoVinculoSistemico($sqTipoVinculoSistemico)
             ->setSqSistema($sqSistema)
             ;
    }

    /**
     * @return string
     * */
    public function getNoTipoVinculoSistemico ()
    {
        return $this->_noTipoVinculoSistemico;
    }

    /**
     * @return integer
     * */
    public function getSqTipoVinculoSistemico ()
    {
        return $this->_sqTipoVinculoSistemico;
    }

    /**
     * @return integer
     * */
    public function getSqSistema ()
    {
        return $this->_sqSistema;
    }

    /**
     * @param string $noTipoVinculoSistemico
     * @return br\gov\mainapp\application\libcorp\tipoVinculo\valueObject\TipoVinculoSistemicoValueObject
     * */
    public function setNoTipoVinculoSistemico ($noTipoVinculoSistemico = NULL)
    {
        $this->_noTipoVinculoSistemico = $noTipoVinculoSistemico;
        return $this;
    }

    /**
     * @param integer $sqTipoVinculoSistemico
     * @return br\gov\mainapp\application\libcorp\tipoVinculo\valueObject\TipoVinculoSistemicoValueObject
     * */
    public function setSqTipoVinculoSistemico ($sqTipoVinculoSistemico = NULL)
    {
        $this->_sqTipoVinculoSistemico = $sqTipoVinculoSistemico;
        return $this;
    }

    /**
     * @param integer $sqSistema
     * @return br\gov\mainapp\application\libcorp\tipoVinculo\valueObject\TipoVinculoSistemicoValueObject
     * */
    public function setSqSistema ($sqSistema = NULL)
    {
        $this->_sqSistema = $sqSistema;
        return $this;
    }
}