<?php
/*
 * Copyright 2011 ICMBio
 * Este arquivo é parte do programa SISICMBio
 * O SISICMBio é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro dos termos
 * da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão
 * 2 da Licença.
 *
 * Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem
 * uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
 * Licença Pública Geral GNU/GPL em português para maiores detalhes.
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENCA.txt",
 * junto com este programa, se não, acesse o Portal do Software Público Brasileiro no endereço
 * www.softwarepublico.gov.br ou escreva para a Fundação do Software Livre(FSF)
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA
 * */
namespace br\gov\mainapp\application\libcorp\banco\valueObject;
use br\gov\sial\core\valueObject\ValueObjectAbstract as ParentValueObject;

/**
  * SISICMBio
  *
  * Generated By SIAL Generator - vs 0.2.0
  *
  * @name TipoTelefoneValueObject
  * @package br.gov.icmbio.sisicmbio.application.libcorp.tipoTelefone
  * @subpackage valueObject
  * @schema(name="corporativo")
  * @entity(name="banco")
  * @author Fabio Lima <fabioolima@gmail.com>
  * @author J. Augusto <augustowebd@gmail.com>
  * @version $Id$
  * @log(name="all")
  * */
class BancoValueObject extends ParentValueObject
{
    /**
     * @attr (
     *  name="noBanco",
     *  database="no_banco",
     *  type="string",
     *  nullable="FALSE",
     *  get="getNoBanco",
     *  set="setNoBanco"
     * )
     * */
     private $_noBanco;

    /**
     * @attr (
     *  name="sqBanco",
     *  database="sq_banco",
     *  primaryKey="TRUE",
     *  type="integer",
     *  nullable="FALSE",
     *  get="getSqBanco",
     *  set="setSqBanco"
     * )
     * */
     private $_sqBanco;

    /**
     * @attr (
     *  name="coBanco",
     *  database="co_banco",
     *  type="string",
     *  get="getCoBanco",
     *  set="setCoBanco"
     * )
     * */
     private $_coBanco;

    /**
     * @param string $noBanco
     * @param integer $sqBanco
     * */
    public function __construct ($noBanco = NULL,
                                 $sqBanco = NULL,
                                 $coBanco = NULL)
    {
        parent::__construct();
        $this->setNoBanco($noBanco)
             ->setSqBanco($sqBanco)
             ->setCoBanco($coBanco)
             ;
    }

    /**
     * @return string
     * */
    public function getNoBanco ()
    {
        return $this->_noBanco;
    }

    /**
     * @return integer
     * */
    public function getSqBanco ()
    {
        return $this->_sqBanco;
    }

    /**
     * @param string $noBanco
     * @return TipoTelefoneValueObject
     * */
    public function setNoBanco ($noBanco = NULL)
    {
        $this->_noBanco = $noBanco;
        return $this;
    }

    /**
     * @param integer $sqBanco
     * @return TipoTelefoneValueObject
     * */
    public function setSqBanco ($sqBanco = NULL)
    {
        $this->_sqBanco = $sqBanco;
        return $this;
    }

    /**
     * Gets the value of _coBanco.
     *
     * @return mixed
     */
    public function getCoBanco()
    {
        return $this->_coBanco;
    }

    /**
     * Sets the value of _coBanco.
     *
     * @param mixed $_coBanco the _co banco
     *
     * @return self
     */
    public function setCoBanco($_coBanco)
    {
        $this->_coBanco = $_coBanco;

        return $this;
    }
}