<?php
/*
 * Copyright 2011 ICMBio
 * Este arquivo é parte do programa SISICMBio
 * O SISICMBio é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro dos termos
 * da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão
 * 2 da Licença.
 *
 * Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem
 * uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
 * Licença Pública Geral GNU/GPL em português para maiores detalhes.
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENCA.txt",
 * junto com este programa, se não, acesse o Portal do Software Público Brasileiro no endereço
 * www.softwarepublico.gov.br ou escreva para a Fundação do Software Livre(FSF)
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA
 * */
namespace br\gov\mainapp\application\libcorp\tipoEscolaridade\valueObject;
use br\gov\sial\core\valueObject\ValueObjectAbstract as ParentValueObject;

/**
  * SISICMBio
  *
  * Generated By SIAL Generator - vs 0.2.0
  *
  * @name TipoTelefoneValueObject
  * @package br.gov.icmbio.sisicmbio.application.libcorp.tipoTelefone
  * @subpackage valueObject
  * @schema(name="corporativo")
  * @entity(name="tipo_escolaridade")
  * @author Fabio Lima <fabioolima@gmail.com>
  * @author J. Augusto <augustowebd@gmail.com>
  * @version $Id$
  * @log(name="all")
  * */
class TipoEscolaridadeValueObject extends ParentValueObject
{
    /**
     * @attr (
     *  name="noTipoEscolaridade",
     *  database="no_tipo_escolaridade",
     *  type="string",
     *  nullable="FALSE",
     *  get="getNoTipoEscolaridade",
     *  set="setNoTipoEscolaridade"
     * )
     * */
     private $_noTipoEscolaridade;

    /**
     * @attr (
     *  name="sqTipoEscolaridade",
     *  database="sq_tipo_escolaridade",
     *  primaryKey="TRUE",
     *  type="integer",
     *  nullable="FALSE",
     *  get="getSqTipoEscolaridade",
     *  set="setSqTipoEscolaridade"
     * )
     * */
     private $_sqTipoEscolaridade;

    /**
     * @param string $noTipoEscolaridade
     * @param integer $sqTipoEscolaridade
     * */
    public function __construct ($noTipoEscolaridade = NULL,
                                 $sqTipoEscolaridade = NULL)
    {
        parent::__construct();
        $this->setNoTipoEscolaridade($noTipoEscolaridade)
             ->setSqTipoEscolaridade($sqTipoEscolaridade)
             ;
    }

    /**
     * @return string
     * */
    public function getNoTipoEscolaridade ()
    {
        return $this->_noTipoEscolaridade;
    }

    /**
     * @return integer
     * */
    public function getSqTipoEscolaridade ()
    {
        return $this->_sqTipoEscolaridade;
    }

    /**
     * @param string $noTipoEscolaridade
     * @return TipoTelefoneValueObject
     * */
    public function setNoTipoEscolaridade ($noTipoEscolaridade = NULL)
    {
        $this->_noTipoEscolaridade = $noTipoEscolaridade;
        return $this;
    }

    /**
     * @param integer $sqTipoEscolaridade
     * @return TipoTelefoneValueObject
     * */
    public function setSqTipoEscolaridade ($sqTipoEscolaridade = NULL)
    {
        $this->_sqTipoEscolaridade = $sqTipoEscolaridade;
        return $this;
    }
}