<?php
/*
 * Copyright 2011 ICMBio
 * Este arquivo é parte do programa SISICMBio
 * O SISICMBio é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro dos termos
 * da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão
 * 2 da Licença.
 *
 * Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem
 * uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
 * Licença Pública Geral GNU/GPL em português para maiores detalhes.
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENCA.txt",
 * junto com este programa, se não, acesse o Portal do Software Público Brasileiro no endereço
 * www.softwarepublico.gov.br ou escreva para a Fundação do Software Livre(FSF)
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA
 * */
namespace br\gov\mainapp\application\libcorp\pais\valueObject;
use br\gov\sial\core\valueObject\ValueObjectAbstract as ParentValueObject;

/**
  * SISICMBio
  *
  * Generated By SIAL Generator - vs 0.2.0
  *
  * @name PaisValueObject
  * @package br.gov.mainapp.application.libcorp.pais
  * @subpackage valueObject
  * @schema(name="corporativo")
  * @entity(name="pais")
  * @author Fabio Lima <fabioolima@gmail.com>
  * @author J. Augusto <augustowebd@gmail.com>
  * @version $Id$
  * @log(name="all")
  * */
class PaisValueObject extends ParentValueObject
{
    /**
     * @attr (
     *  name="sqPais",
     *  database="sq_pais",
     *  primaryKey="TRUE",
     *  type="integer",
     *  nullable="FALSE",
     *  get="getSqPais",
     *  set="setSqPais"
     * )
     * */
     private $_sqPais;

    /**
     * @attr (
     *  name="noPais",
     *  database="no_pais",
     *  type="string",
     *  nullable="FALSE",
     *  get="getNoPais",
     *  set="setNoPais"
     * )
     * */
     private $_noPais;

    /**
     * @attr (
     *  name="inFazFronteira",
     *  database="in_faz_fronteira",
     *  type="boolean",
     *  nullable="FALSE",
     *  get="getInFazFronteira",
     *  set="setInFazFronteira"
     * )
     * */
     private $_inFazFronteira;

    /**
     * @param integer $sqPais
     * @param string $noPais
     * @param boolean $inFazFronteira
     * */
    public function __construct ($sqPais         = NULL,
                                 $noPais         = NULL,
                                 $inFazFronteira = NULL)
    {
        parent::__construct();
        $this->setSqPais($sqPais)
             ->setNoPais($noPais)
             ->setInFazFronteira($inFazFronteira)
             ;
    }

	/**
     * (non-PHPdoc)
     * Utilizado pois em Pais existe a chamada deste método, devido a persistencia chamar automaticamente
     * é necessário fazer o apelido aqui !!
     * @see br\gov\icmbio\sial.SIALAbstract::__call()
     */
    public function __call ($name, $args)
    {
        if ('getSqNacionalidade' == $name) {
            return $this->getSqPais();
        }
    }

    /**
     * @return integer
     * */
    public function getSqPais ()
    {
        return $this->_sqPais;
    }

    /**
     * @return string
     * */
    public function getNoPais ()
    {
        return $this->_noPais;
    }

    /**
     * @return boolean
     */
    public function getInFazFronteira ()
    {
        return $this->_inFazFronteira;
    }

    /**
     * @param integer $sqPais
     * @return br\gov\icmbio\sisicmbio\application\libcorp\pais\valueObject\PaisValueObject
     * */
    public function setSqPais ($sqPais = NULL)
    {
        $this->_sqPais = $sqPais;
        return $this;
    }

    /**
     * @param string $noPais
     * @return br\gov\icmbio\sisicmbio\application\libcorp\pais\valueObject\PaisValueObject
     * */
    public function setNoPais ($noPais = NULL)
    {
        $this->_noPais = $noPais;
        return $this;
    }

    /**
     * @param boolean $inFazFronteira
     * @return br\gov\icmbio\sisicmbio\application\libcorp\pais\valueObject\PaisValueObject
     */
    public function setInFazFronteira ($inFazFronteira = NULL)
    {
        $this->_inFazFronteira = $inFazFronteira;
        return $this;
    }
}