<?php

    $view = $this;

    $acao = function($row) use ($view) {
            $rtn = $view->actionButton('Excluir', 'ListaPeca.deletar', array($row['sqArtefatoVinculo'],$row['nuDigital'],$row['inOriginal']),'trash');
            return $rtn;
    };

    $noTipoVinculoArtefato = function($row) use ($view) {
    	if($row['inOriginal']){
    		return 'Original';
    	}else{
    		return 'Cópia';
    	}
    };

    $numero = function ($row) use ($view) {
        return  ($row['nuDigital'] == NULL) ? $row['nuArtefato'] : $row['nuDigital'];
    };

    $configArray = array('columns' => array(
                         0 =>array( 'column' => $numero),
                         1 =>array( 'column' => $noTipoVinculoArtefato),
                         2 =>array( 'column' => $acao)

    ));

    $this->grid->setConfig($configArray);
    $data  = $this->grid->parseData($this->result);

    echo json_encode($data);