<?php
/*
 * Copyright 2011 ICMBio
 * Este arquivo é parte do programa SISICMBio
 * O SISICMBio é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro dos termos
 * da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão
 * 2 da Licença.
 *
 * Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem
 * uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
 * Licença Pública Geral GNU/GPL em português para maiores detalhes.
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENCA.txt",
 * junto com este programa, se não, acesse o Portal do Software Público Brasileiro no endereço
 * www.softwarepublico.gov.br ou escreva para a Fundação do Software Livre(FSF)
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA
 * */
namespace br\gov\mainapp\application\libcorp\cargo\valueObject;
use br\gov\sial\core\valueObject\ValueObjectAbstract as ParentValueObject;

/**
  * SISICMBio
  *
  * Generated By SIAL Generator - vs 0.2.0
  *
  * @name CargoValueObject
  * @package br.gov.icmbio.sisicmbio.application.sica.cargo
  * @subpackage valueObject
  * @schema(name="corporativo")
  * @entity(name="cargo")
  * @author Fabio Lima <fabioolima@gmail.com>
  * @author J. Augusto <augustowebd@gmail.com>
  * @version $Id$
  * @log(name="all")
  * */
class CargoValueObject extends ParentValueObject
{
    /**
     * @attr (
     *  name="sqCargo",
     *  database="sq_cargo",
     *  primaryKey="TRUE",
     *  type="integer",
     *  nullable="FALSE",
     *  get="getSqCargo",
     *  set="setSqCargo"
     * )
     * */
     private $_sqCargo;

    /**
     * @attr (
     *  name="noCargo",
     *  database="no_cargo",
     *  type="string",
     *  nullable="FALSE",
     *  get="getNoCargo",
     *  set="setNoCargo"
     * )
     * */
     private $_noCargo;

    /**
     * @param integer $sqCargo
     * @param string $noCargo
     * */
    public function __construct ($sqCargo = NULL,
                                 $noCargo = NULL)
    {
        parent::__construct();
        $this->setSqCargo($sqCargo)
             ->setNoCargo($noCargo)
             ;
    }

    /**
     * @return integer
     * */
    public function getSqCargo ()
    {
        return $this->_sqCargo;
    }

    /**
     * @return string
     * */
    public function getNoCargo ()
    {
        return $this->_noCargo;
    }

    /**
     * @param integer $sqCargo
     * @return CargoValueObject
     * */
    public function setSqCargo ($sqCargo = NULL)
    {
        $this->_sqCargo = $sqCargo;
        return $this;
    }

    /**
     * @param string $noCargo
     * @return CargoValueObject
     * */
    public function setNoCargo ($noCargo = NULL)
    {
        $this->_noCargo = $noCargo;
        return $this;
    }
}