<?php $data = $this->layout()->data; ?>
<?php
$assetUrl = new Core_View_Helper_AssetUrl();
$assetUrl->setView($this);
$path = APPLICATION_PATH . '/../public/';

$this->headLink()
        ->setStylesheet($path . $assetUrl->assetUrl('style.css', true, array('address' => 'asset')))
        ->appendStylesheet($path . $assetUrl->assetUrl('style-correct.css', true, array('address' => 'asset')))
        ->appendStylesheet($path . $assetUrl->assetUrl('style-responsive.css', true, array('address' => 'asset')))
        ->appendStylesheet($path . $assetUrl->assetUrl('style.css', true))
        ->appendStylesheet($path . $assetUrl->assetUrl('pdf.css', true))
        ->appendStylesheet($path . $assetUrl->assetUrl('pdf-sistema.css', true));

echo $this->headLink();
?>

<page backtop="2mm" backbottom="3mm" backleft="3mm" backright="3mm">
    <page_footer>
        <div class="content">
            <table class="table-footer">
                <tr>
                    <td class="data">
                        Data: <?php echo date('d/m/Y') . ' às ' . date('H') . 'h' . date('i'); ?>
                    </td>
                    <td class="responsavel">
                        Responsável: <?php echo \Core_Integration_Sica_User::getUserName(); ?>
                    </td>
                    <td class="paginacao">
                        Página [[page_cu]] de [[page_nb]]
                    </td>
                </tr>
            </table>
        </div>
    </page_footer>
    <div class="content">
        <div>
            <img src="<?php echo $path . $assetUrl->assetUrl('icons/marcaICMBioBig.png', true, array('address' => 'asset')) ?>" name="figura1" class="pull-left" width="100" border="0" />
            <span align="center">
                <h3>SICA-e - Sistema de Integra&ccedil;&atilde;o e Controle de Acesso</h3>
                <h4 align="center">Resultado da Pesquisa de Menu</h4>
            </span>
        </div>
        <br/>
        <br/>
        <table class="table table-condensed" id="table-pdf">
            <thead>
                <tr class="title">
                    <td colspan="2">
                        <strong><?php echo $data['sistema']['sgSistema'] ?> - <?php echo $data['sistema']['noSistema'] ?></strong>
                    </td>
                </tr>
                <tr class="title">
                    <td>
                        Menu
                    </td>
                    <td>
                        Status
                    </td>
                </tr>
            </thead>
            <tbody>
                <?php unset($data['sistema']); ?>
                <?php foreach ($data as $key => $value) : ?>
                    <?php
                    $label = $value['noMenu'];
                    $label = ($value['nuNivel'] > 1) ? '<i class="icon-subnivel subnivel"></i>' . $label : $label;
                    $label = str_repeat('&nbsp;', $value['nuNivel'] * ($value['nuNivel'] - 1)) . $label;
                    ?>
                    <tr class="<?php echo ($key % 2) ? 'odd' : 'even'; ?>">
                        <td>
                            <?php echo $label; ?>
                        </td>
                        <td>
                            <?php echo $value['stRegistroAtivo'] ? 'Ativo' : 'Inativo' ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                <tr>
                    <td colspan="2" class="total-registro">
                        Total de Registros: <?php echo count($data); ?>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</page>