<?php
/*
 * Copyright 2011 ICMBio
 * Este arquivo é parte do programa SISICMBio
 * O SISICMBio é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro dos termos
 * da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão
 * 2 da Licença.
 *
 * Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem
 * uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
 * Licença Pública Geral GNU/GPL em português para maiores detalhes.
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENCA.txt",
 * junto com este programa, se não, acesse o Portal do Software Público Brasileiro no endereço
 * www.softwarepublico.gov.br ou escreva para a Fundação do Software Livre(FSF)
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA
 * */
namespace br\gov\mainapp\application\libcorp\cadastroSemCPF\valueObject;
use br\gov\sial\core\valueObject\ValueObjectAbstract as ParentValueObject,
    br\gov\mainapp\application\libcorp\pessoa\mvcb\business\PessoaBusiness;

/**
  * SISICMBio
  *
  * Generated By SIAL Generator - vs 0.2.0
  *
  * @name CadastroSemCPFValueObject
  * @package br.gov.mainapp.application.libcorp.cadastroSemCPF
  * @subpackage valueObject
  * @schema(name="corporativo")
  * @entity(name="cadastro_sem_cpf")
  * @author Fabio Lima <fabioolima@gmail.com>
  * @author J. Augusto <augustowebd@gmail.com>
  * @version $Id$
  * @log(name="all")
  * */
class CadastroSemCPFValueObject extends ParentValueObject
{
    /**
     * @attr (
     *  name="sqPessoa",
     *  database="sq_pessoa",
     *  type="integer",
     *  nullable="FALSE",
     *  get="getSqPessoa",
     *  set="setSqPessoa"
     * )
     * */
     private $_sqPessoa;

    /**
     * @attr (
     *  name="dtInclusao",
     *  database="dt_inclusao",
     *  type="string",
     *  nullable="FALSE",
     *  get="getDtInclusao",
     *  set="setDtInclusao"
     * )
     * */
     private $_dtInclusao;

    /**
     * @attr (
     *  name="sqPessoaAutora",
     *  database="sq_pessoa_autora",
     *  type="integer",
     *  nullable="FALSE",
     *  get="getSqPessoaAutora",
     *  set="setSqPessoaAutora"
     * )
     * */
     private $_sqPessoaAutora;

    /**
     * @attr (
     *  name="txJustificativa",
     *  database="tx_justificativa",
     *  type="string",
     *  nullable="FALSE",
     *  get="getTxJustificativa",
     *  set="setTxJustificativa"
     * )
     * */
     private $_txJustificativa;

     /**
     * @attr (
     *  name="sqCadastroSemCPF",
     *  database="sq_cadastro_sem_cpf",
     *  primaryKey="TRUE",
     *  type="integer",
     *  nullable="FALSE",
     *  get="getSqCadastroSemCPF",
     *  set="setSqCadastroSemCPF"
     * )
     * */
     private $_sqCadastroSemCPF;

    /**
     * @attr (
     *  name="sqPessoaAutoriza",
     *  database="sq_pessoa_autoriza",
     *  type="integer",
     *  nullable="TRUE",
     *  get="getSqPessoaAutoriza",
     *  set="setSqPessoaAutoriza"
     * )
     * */
     private $_sqPessoaAutoriza;

    /**
     * @param integer $sqCadastroSemCPF
     * @param integer $sqPessoa
     * @param string $dtInclusao
     * @param integer $sqPessoaAutora
     * @param string $txJustificativa
     * @param integer $sqPessoaAutoriza
     * */
    public function __construct ($sqCadastroSemCPF = NULL,
                                   $sqPessoa         = NULL,
                                   $dtInclusao       = NULL,
                                   $sqPessoaAutora   = NULL,
                                   $txJustificativa  = NULL,
                                   $sqPessoaAutoriza = NULL)
    {
        parent::__construct();

        $this->setSqCadastroSemCPF($sqCadastroSemCPF)
             ->setSqPessoa($sqPessoa)
             ->setDtInclusao($dtInclusao)
             ->setSqPessoaAutora($sqPessoaAutora)
             ->setSqPessoaAutoriza($sqPessoaAutoriza)
             ->setTxJustificativa($txJustificativa)
        ;
    }

    /**
     * @return integer
     * */
    public function getSqCadastroSemCPF ()
    {
        return $this->_sqCadastroSemCPF;
    }

    /**
     * @return \br\gov\mainapp\application\libcorp\pessoa\valueObject\PessoaValueObject
     * */
    public function getSqPessoa ()
    {
        if ((NULL != $this->_sqPessoa) && !($this->_sqPessoa instanceof parent)) {
            $this->_sqPessoa = PessoaBusiness::factory(NULL, 'libcorp')->find($this->_sqPessoa);
        }
        return $this->_sqPessoa;
    }

    /**
     * @return string
     * */
    public function getDtInclusao ()
    {
        return $this->_dtInclusao;
    }

    /**
     * @return integer
     * */
    public function getTxJustificativa ()
    {
        return $this->_txJustificativa;
    }

    /**
     * @return integer
     * */
    public function getSqPessoaAutoriza ()
    {
        return $this->_sqPessoaAutoriza;
    }

    /**
     * @return mixed
     */
    public function getSqPessoaAutora()
    {
        return $this->_sqPessoaAutora;
    }

    /**
     * @param integer $sqCadastroSemCPF
     * @return br\gov\icmbio\sisicmbio\application\sica\cadastroSemCPF\valueObject\CadastroSemCPFValueObject
     * */
    public function setSqCadastroSemCPF ($sqCadastroSemCPF = NULL)
    {
        $this->_sqCadastroSemCPF = $sqCadastroSemCPF;
        return $this;
    }

    /**
     * @param integer $sqPessoa
     * @return br\gov\icmbio\sisicmbio\application\sica\cadastroSemCPF\valueObject\CadastroSemCPFValueObject
     * */
    public function setSqPessoa ($sqPessoa = NULL)
    {
        $this->_sqPessoa = $sqPessoa;
        return $this;
    }

    /**
     * @param integer $dtInclusao
     * @return br\gov\icmbio\sisicmbio\application\sica\cadastroSemCPF\valueObject\CadastroSemCPFValueObject
     * */
    public function setDtInclusao ($dtInclusao = NULL)
    {
        $this->_dtInclusao = $dtInclusao;
        return $this;
    }

    /**
     * @param mixed $sqPessoaAutora
     */
    public function setSqPessoaAutora($sqPessoaAutora = NULL)
    {
        $this->_sqPessoaAutora = $sqPessoaAutora;
        return $this;
    }

    /**
     * @param integer $txJustificativa
     * @return br\gov\icmbio\sisicmbio\application\sica\cadastroSemCPF\valueObject\CadastroSemCPFValueObject
     * */
    public function setTxJustificativa ($txJustificativa = NULL)
    {
        $this->_txJustificativa = $txJustificativa;
        return $this;
    }

    /**
     * @return integer
     * */
    public function setSqPessoaAutoriza ($sqPessoaAutoriza = NULL)
    {
        $this->_sqPessoaAutoriza = $sqPessoaAutoriza;
        return $this;
    }
}
