<?php
/*
 * Copyright 2011 ICMBio
 * Este arquivo é parte do programa SISICMBio
 * O SISICMBio é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro dos termos
 * da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão
 * 2 da Licença.
 *
 * Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem
 * uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
 * Licença Pública Geral GNU/GPL em português para maiores detalhes.
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENCA.txt",
 * junto com este programa, se não, acesse o Portal do Software Público Brasileiro no endereço
 * www.softwarepublico.gov.br ou escreva para a Fundação do Software Livre(FSF)
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA
 * */
namespace br\gov\mainapp\application\libcorp\situacaoFuncional\valueObject;
use br\gov\sial\core\valueObject\ValueObjectAbstract as ParentValueObject;

/**
  * SISICMBio
  *
  * Generated By SIAL Generator - vs 0.2.0
  *
  * @name CargoValueObject
  * @package br.gov.icmbio.sisicmbio.application.sica.cargo
  * @subpackage valueObject
  * @schema(name="corporativo")
  * @entity(name="situacao_funcional")
  * @author Fabio Lima <fabioolima@gmail.com>
  * @author J. Augusto <augustowebd@gmail.com>
  * @version $Id$
  * @log(name="all")
  * */
class SituacaoFuncionalValueObject extends ParentValueObject
{
    /**
     * @attr (
     *  name="sqSituacaoFuncional",
     *  database="sq_situacao_funcional",
     *  primaryKey="TRUE",
     *  type="integer",
     *  nullable="FALSE",
     *  get="getSqSituacaoFuncional",
     *  set="setSqSituacaoFuncional"
     * )
     * */
     private $_sqSituacaoFuncional;

    /**
     * @attr (
     *  name="noSituacaoFuncional",
     *  database="no_situacao_funcional",
     *  type="string",
     *  nullable="FALSE",
     *  get="getNoSituacaoFuncional",
     *  set="setNoSituacaoFuncional"
     * )
     * */
     private $_noSituacaoFuncional;

    /**
     * @param integer $sqSituacaoFuncional
     * @param string $noSituacaoFuncional
     * */
    public function __construct ($sqSituacaoFuncional = NULL,
                                 $noSituacaoFuncional = NULL)
    {
        parent::__construct();
        $this->setSqSituacaoFuncional($sqSituacaoFuncional)
             ->setNoSituacaoFuncional($noSituacaoFuncional)
             ;
    }

    /**
     * @return integer
     * */
    public function getSqSituacaoFuncional ()
    {
        return $this->_sqSituacaoFuncional;
    }

    /**
     * @return string
     * */
    public function getNoSituacaoFuncional ()
    {
        return $this->_noSituacaoFuncional;
    }

    /**
     * @param integer $sqSituacaoFuncional
     * @return CargoValueObject
     * */
    public function setSqSituacaoFuncional ($sqSituacaoFuncional = NULL)
    {
        $this->_sqSituacaoFuncional = $sqSituacaoFuncional;
        return $this;
    }

    /**
     * @param string $noSituacaoFuncional
     * @return CargoValueObject
     * */
    public function setNoSituacaoFuncional ($noSituacaoFuncional = NULL)
    {
        $this->_noSituacaoFuncional = $noSituacaoFuncional;
        return $this;
    }
}