<?php
/*
         * Copyright 2012 ICMBio
         * Este arquivo é parte do programa SISICMBio
         * O SISICMBio é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro dos termos
         * da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão
         * 2 da Licença.
         *
         * Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem
         * uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
         * Licença Pública Geral GNU/GPL em português para maiores detalhes.
         * Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENCA.txt",
         * junto com este programa, se não, acesse o Portal do Software Público Brasileiro no endereço
         * www.softwarepublico.gov.br ou escreva para a Fundação do Software Livre(FSF)
         * Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA
         * */

namespace Sgdoce\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UnidadeOrgExterna
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VwUnidadeOrgExterna extends \Core_Model_Repository_Base
{
    /**
     * método que pesquisa unidades organizacinais externas para combo
     * @param array $params
     * @return array $out
     */
    public function searchUnidadesOrganizacionaisExternas ($params, $limit = 10)
    {
        $search       = mb_strtolower($params->getQuery(),'UTF-8');
        $queryBuilder = $this->_em->createQueryBuilder();

        $query = $queryBuilder->select('p.sqPessoa, p.noPessoa')
            ->from('app:VwUnidadeOrgExterna', 'u')
            ->innerJoin('u.sqPessoa','p');

        $field = $queryBuilder->expr()
            ->lower($queryBuilder->expr()->trim('p.noPessoa'));

        $query->andWhere(
            $queryBuilder->expr()
                ->like(
                    'clear_accentuation(' . $field .')',
                    $queryBuilder->expr()
                        ->literal($this->removeAccent('%' . $search . '%'))
                )
        )
            ->orderBy('p.noPessoa')
            ->setMaxResults($limit);

        $res = $query->getQuery()->getArrayResult();
        $out = array();
        foreach ($res as $item) {
            $out[$item['sqPessoa']]= $item['noPessoa'];
        }

        return $out;
    }
}