<?php

$view = $this;

$acao = function($row) use ($view) {
    return $view->actionButton('Rastrear', 'ModalRastremanto.trace', array('txCodigoRastreamento' => strtoupper($row['txCodigoRastreamento'])), 'envelope', NULL);
};

$fnDtEnvio = function($row) {
    return $row['dtEnvio']->toString('dd/MM/YYYY');
};

$configArray = array('columns' => array(
         array('column' => 'noPessoaDestino')
        ,array('column' => 'noTipoRastreamento')
        ,array('column' => 'txCodigoRastreamento')
        ,array('column' => $fnDtEnvio)
        ,array('column' => 'noRemetente')
        ,array('column' => $acao)
    ));

$this->grid->setConfig($configArray);
$data = $this->grid->parseData($this->result);

echo json_encode($data);
