<?php if($this->exception) { ?>
<div class="row-fluid">
    <div class="span12">
        <h2>Erro no XML</h2>
        <h4><?php echo $this->mensagem; ?></h4>
    </div>
</div>
    <div class="row-fluid">
        <div class="span12">
            <br>
            <pre>
            <?php
                var_dump($this->stringXml);
            ?>
        </div>
    </div>
<?php } else { ?>
<div class="span9">
    <h2>Verificação de Log</h2>
</div>
<br>
<form class="form-horizontal form-processo-eletronico" name="form-create" action="/log/detalhe" method="post">
    <br>
    <br>
    <div class="control-group">
        <label for="nuDigital" class="control-label"> Codigo
        </label>
        <div class="controls">
            <div class="input-append">
                <input type="text" maxlength="15" id="id" name="id" class="input-large">
            </div>
        </div>
    </div>
    <div class="form-actions" id="formButtonsPrincipal">
        <button type="submit" class="btn btn-primary">Buscar</button>
    </div>
</form>
<div class="row-fluid">
    <div class="span12">
        <div role="grid" class="dataTables_wrapper form-inline" id="table-grid_wrapper">
            <table class="table table-striped table-bordered ">
                <thead>
                    <th>Cod</th>
                    <th>Tabela</th>
                    <th>Data</th>
                    <th>Usuário</th>
                    <th>Operação</th>
                </thead>
                <tbody>
                <tr>
                    <td><?php echo $this->trilha['sqAuditoria'];?></td>
                    <td><?php echo $this->xml->tabela->nome ?></td>
                    <td><?php echo $this->trilha['dtDataHora'];?></td>
                    <td><?php echo $this->trilha['sqUsuario'];?></td>
                    <td>
                    <?php
                        switch ($this->trilha['sgOperacao']) {
                            case "I": echo 'INSERÇÃO'; break;
                            case "U": echo 'ALTERAÇÃO'; break;
                            case "D": echo 'EXCLUSÃO'; break;
                            default: echo $this->trilha['sgOperacao'];
                        }
                    ?>
                    </td>
                </tr>
                <tr>
                    <td><b>Rota</b></td>
                    <td colspan="4"><?php echo $this->xml->rota ?></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row-fluid">
<div class="span6">
    <h4>Log</h4><br>
    <div role="grid" class="dataTables_wrapper form-inline" id="table-grid_wrapper">
        <table class="table table-striped table-bordered ">
            <thead>
                <tr>
                    <th>Campo</th>
                    <th>Valor</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($this->colunas as $coluna => $valor) { ?>
            <?php
                $erro = false;
                if (!array_key_exists($coluna, $this->tabela)) {
                    $erro = true;
                }
                if (isset($this->tabela[$coluna]) && $this->tabela[$coluna] != $valor) {
                    $erro = true;
                    if (empty($this->tabela[$coluna]) && empty($this->coluna[$coluna])) {
                        $erro = false;
                    }
                }
            ?>
            <tr <?php echo ($erro) ? "style='color:red'" : ''?>>
                <td><?php echo $coluna ?></td>
                <td><?php echo $valor ?></td>
            </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>
<div class="span6">
    <h4>Tabela</h4><br>
    <div role="grid" class="dataTables_wrapper form-inline" id="table-grid_wrapper">
        <table class="table table-striped table-bordered ">
            <thead>
                <th>Campo</th>
                <th>Valor</th>
            </thead>
            <tbody>
            <?php foreach ($this->tabela as $campo => $valor) { ?>
            <?php
                $erro = false;
                if (!array_key_exists($campo, $this->colunas)) {
                    $erro = true;
                }
                if (isset($this->colunas[$campo]) && $this->colunas[$campo] != $valor) {
                    $erro = true;
                    if (empty($this->colunas[$campo]) && empty($this->tabela[$campo])) {
                        $erro = false;
                    }
                }
            ?>
            <tr <?php echo ($erro) ? "style='color:red'" : ''?>>
                <td><?php echo $campo ?></td>
                <td><?php echo $valor ?></td>
            </tr>

            <?php } ?>
            </tbody>
        </table>
    </div>
</div>

</div>

<?php } ?>



