<?php
/*
 * Copyright 2011 ICMBio
 * Este arquivo é parte do programa SISICMBio
 * O SISICMBio é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro dos termos
 * da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão
 * 2 da Licença.
 *
 * Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem
 * uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
 * Licença Pública Geral GNU/GPL em português para maiores detalhes.
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENCA.txt",
 * junto com este programa, se não, acesse o Portal do Software Público Brasileiro no endereço
 * www.softwarepublico.gov.br ou escreva para a Fundação do Software Livre(FSF)
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA
 * */
namespace br\gov\mainapp\application\libcorp\vinculoSistemico\mvcb\business;
use br\gov\sial\core\lang\Date,
    br\gov\sial\core\valueObject\ValueObjectAbstract,
    br\gov\sial\core\mvcb\business\BusinessCrudAbstract as ParentBusiness;

/**
  * SISICMBio
  *
  * Generated By SIAL Generator - vs 0.2.0
  *
  * @name VinculoSistemicoBusiness
  * @package br.gov.icmbio.sisicmbio.application.sica.vinculoSistemico.mvcb
  * @subpackage business
  * @author Fabio Lima <fabioolima@gmail.com>
  * @version $Id$
  * */
class VinculoSistemicoBusiness extends ParentBusiness
{
    public function save (ValueObjectAbstract $valueObject)
    {
        $this->translateDate($valueObject);
        return $this->getModel()->save($valueObject);
    }

    public function update (ValueObjectAbstract $valueObject)
    {
        $this->translateDate($valueObject);
        return $this->getModel()->update($valueObject);
    }


    private function translateDate (ValueObjectAbstract $valueObject)
    {
        $dtIni = $valueObject->getDtInicioVinculo();
        $dtFin = $valueObject->getDtFimVinculo();

        if ($dtIni) { $valueObject->setDtInicioVinculo(Date::factory($dtIni, 'd/m/Y')->output()) ; }
        if ($dtFin) { $valueObject->setDtFimVinculo(Date::factory($dtFin, 'd/m/Y')->output());     }
    }
}