<?php
/*
 * Copyright 2011 ICMBio
 * Este arquivo é parte do programa SISICMBio
 * O SISICMBio é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro dos termos
 * da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão
 * 2 da Licença.
 *
 * Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem
 * uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
 * Licença Pública Geral GNU/GPL em português para maiores detalhes.
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENCA.txt",
 * junto com este programa, se não, acesse o Portal do Software Público Brasileiro no endereço
 * www.softwarepublico.gov.br ou escreva para a Fundação do Software Livre(FSF)
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA
 * */
namespace br\gov\mainapp\application\libcorp\vinculoFuncional\valueObject;
use br\gov\sial\core\valueObject\ValueObjectAbstract as ParentValueObject;

/**
  * SISICMBio
  *
  * Generated By SIAL Generator - vs 0.2.0
  *
  * @name CargoValueObject
  * @package br.gov.icmbio.sisicmbio.application.sica.cargo
  * @subpackage valueObject
  * @schema(name="corporativo")
  * @entity(name="vinculo_funcional")
  * @author Fabio Lima <fabioolima@gmail.com>
  * @version $Id$
  * @log(name="all")
  * */
class VinculoFuncionalValueObject extends ParentValueObject
{
    /**
     * @attr (
     *  name="sqVinculoFuncional",
     *  database="sq_vinculo_funcional",
     *  primaryKey="TRUE",
     *  type="integer",
     *  nullable="FALSE",
     *  get="getSqVinculoFuncional",
     *  set="setSqVinculoFuncional"
     * )
     * */
     private $_sqVinculoFuncional;

    /**
     * @attr (
     *  name="sqPessoa",
     *  database="sq_pessoa",
     *  type="integer",
     *  nullable="FALSE",
     *  get="getSqPessoa",
     *  set="setSqPessoa"
     * )
     * */
     private $_sqPessoa;

    /**
     * @attr (
     *  name="sqUnidadeLotacao",
     *  database="sq_unidade_lotacao",
     *  type="integer",
     *  get="getSqUnidadeLotacao",
     *  set="setSqUnidadeLotacao"
     * )
     * */
     private $_sqUnidadeLotacao;

    /**
     * @attr (
     *  name="sqUnidadeExercicio",
     *  database="sq_unidade_exercicio",
     *  type="integer",
     *  nullable="FALSE",
     *  get="getSqUnidadeExercicio",
     *  set="setSqUnidadeExercicio"
     * )
     * */
     private $_sqUnidadeExercicio;

    /**
     * @attr (
     *  name="sqSituacaoFuncional",
     *  database="sq_situacao_funcional",
     *  type="integer",
     *  nullable="FALSE",
     *  get="getSqSituacaoFuncional",
     *  set="setSqSituacaoFuncional"
     * )
     * */
     private $_sqSituacaoFuncional;

    /**
     * @attr (
     *  name="sqCargo",
     *  database="sq_cargo",
     *  type="integer",
     *  get="getSqCargo",
     *  set="setSqCargo"
     * )
     * */
     private $_sqCargo;

    /**
     * @attr (
     *  name="sqFuncao",
     *  database="sq_funcao",
     *  type="integer",
     *  get="getSqFuncao",
     *  set="setSqFuncao"
     * )
     * */
     private $_sqFuncao;

    /**
     * @attr (
     *  name="sqAtribuicao",
     *  database="sq_atribuicao",
     *  type="integer",
     *  get="getSqAtribuicao",
     *  set="setSqAtribuicao"
     * )
     * */
     private $_sqAtribuicao;

    /**
     * @attr (
     *  name="sqIndFimVinculo",
     *  database="sq_ind_fim_vinculo",
     *  type="integer",
     *  get="getSqIndFimVinculo",
     *  set="setSqIndFimVinculo"
     * )
     * */
     private $_sqIndFimVinculo;

    /**
     * @attr (
     *  name="dtInicioVinculo",
     *  database="dt_inicio_vinculo",
     *  type="string",
     *  nullable="FALSE",
     *  get="getDtInicioVinculo",
     *  set="setDtInicioVinculo"
     * )
     * */
     private $_dtInicioVinculo;

    /**
     * @attr (
     *  name="nuMatricula",
     *  database="nu_matricula",
     *  type="integer",
     *  get="getNuMatricula",
     *  set="setNuMatricula"
     * )
     * */
     private $_nuMatricula;

    /**
     * @param integer $sqVinculoFuncional
     * @param string $sqPessoa
     * */
    public function __construct ($sqVinculoFuncional = NULL,
                                 $sqPessoa = NULL)
    {
        parent::__construct();
        $this->setSqVinculoFuncional($sqVinculoFuncional)
             ->setSqPessoa($sqPessoa)
             ;
    }

    /**
     * Gets the value of _sqVinculoFuncional.
     *
     * @return mixed
     */
    public function getSqVinculoFuncional()
    {
        return $this->_sqVinculoFuncional;
    }
    
    /**
     * Gets the value of _sqPessoa.
     *
     * @return mixed
     */
    public function getSqPessoa()
    {
        return $this->_sqPessoa;
    }
    
    /**
     * Gets the value of _sqUnidadeLotacao.
     *
     * @return mixed
     */
    public function getSqUnidadeLotacao()
    {
        return $this->_sqUnidadeLotacao;
    }
    
    /**
     * Gets the value of _sqUnidadeExercicio.
     *
     * @return mixed
     */
    public function getSqUnidadeExercicio()
    {
        return $this->_sqUnidadeExercicio;
    }
    
    /**
     * Gets the value of _sqSituacaoFuncional.
     *
     * @return mixed
     */
    public function getSqSituacaoFuncional()
    {
        return $this->_sqSituacaoFuncional;
    }
    
    /**
     * Gets the value of _sqCargo.
     *
     * @return mixed
     */
    public function getSqCargo()
    {
        return $this->_sqCargo;
    }
    
    /**
     * Gets the value of _sqFuncao.
     *
     * @return mixed
     */
    public function getSqFuncao()
    {
        return $this->_sqFuncao;
    }
    
    /**
     * Gets the value of _sqAtribuicao.
     *
     * @return mixed
     */
    public function getSqAtribuicao()
    {
        return $this->_sqAtribuicao;
    }
    
    /**
     * Gets the value of _sqIndFimVinculo.
     *
     * @return mixed
     */
    public function getSqIndFimVinculo()
    {
        return $this->_sqIndFimVinculo;
    }
    
    /**
     * Gets the value of _nuMatricula.
     *
     * @return mixed
     */
    public function getNuMatricula()
    {
        return $this->_nuMatricula;
    }

    /**
     * Gets the value of _nuMatricula.
     *
     * @return mixed
     */
    public function getDtInicioVinculo()
    {
        return $this->_dtInicioVinculo;
    }

    /**
     * Sets the value of _sqVinculoFuncional.
     *
     * @param mixed $_sqVinculoFuncional the _sq vinculo funcional
     *
     * @return self
     */
    public function setSqVinculoFuncional($_sqVinculoFuncional)
    {
        $this->_sqVinculoFuncional = $_sqVinculoFuncional;

        return $this;
    }

    /**
     * Sets the value of _sqPessoa.
     *
     * @param mixed $_sqPessoa the _sq pessoa
     *
     * @return self
     */
    public function setSqPessoa($_sqPessoa)
    {
        $this->_sqPessoa = $_sqPessoa;

        return $this;
    }

    /**
     * Sets the value of _sqUnidadeLotacao.
     *
     * @param mixed $_sqUnidadeLotacao the _sq unidade lotacao
     *
     * @return self
     */
    public function setSqUnidadeLotacao($_sqUnidadeLotacao)
    {
        $this->_sqUnidadeLotacao = $_sqUnidadeLotacao;

        return $this;
    }

    /**
     * Sets the value of _sqUnidadeExercicio.
     *
     * @param mixed $_sqUnidadeExercicio the _sq unidade exercicio
     *
     * @return self
     */
    public function setSqUnidadeExercicio($_sqUnidadeExercicio)
    {
        $this->_sqUnidadeExercicio = $_sqUnidadeExercicio;

        return $this;
    }

    /**
     * Sets the value of _sqSituacaoFuncional.
     *
     * @param mixed $_sqSituacaoFuncional the _sq situacao funcional
     *
     * @return self
     */
    public function setSqSituacaoFuncional($_sqSituacaoFuncional)
    {
        $this->_sqSituacaoFuncional = $_sqSituacaoFuncional;

        return $this;
    }

    /**
     * Sets the value of _sqCargo.
     *
     * @param mixed $_sqCargo the _sq cargo
     *
     * @return self
     */
    public function setSqCargo($_sqCargo)
    {
        $this->_sqCargo = $_sqCargo;

        return $this;
    }

    /**
     * Sets the value of _sqFuncao.
     *
     * @param mixed $_sqFuncao the _sq funcao
     *
     * @return self
     */
    public function setSqFuncao($_sqFuncao)
    {
        $this->_sqFuncao = $_sqFuncao;

        return $this;
    }

    /**
     * Sets the value of _sqAtribuicao.
     *
     * @param mixed $_sqAtribuicao the _sq atribuicao
     *
     * @return self
     */
    public function setSqAtribuicao($_sqAtribuicao)
    {
        $this->_sqAtribuicao = $_sqAtribuicao;

        return $this;
    }

    /**
     * Sets the value of _sqAtribuicao.
     *
     * @param mixed $_sqAtribuicao the _sq atribuicao
     *
     * @return self
     */
    public function setDtInicioVinculo($dtInicioVinculo)
    {
        $this->_dtInicioVinculo = $dtInicioVinculo;

        return $this;
    }
}