<?php

$view = $this;

$acao = function($row) use ($view) {
            $codigo = array($row['sqEmail'], $row['sqPessoa']);

            $button = $view->actionButton('Alterar', 'Email.alterar', $codigo, 'pencil')
                    . $view->actionButton('Excluir', 'Email.deletar', $codigo, 'trash');

            return $button;
        };

$configArray = array();
$configArray['columns'][0]['column'] = 'noTipoEmail';
$configArray['columns'][1]['column'] = 'txEmail';
$configArray['columns'][2]['column'] = $acao;

$this->grid->setConfig($configArray);
$data = $this->grid->parseData($this->result);

echo json_encode($data);