<?php

/*
 * Copyright 2013 ICMBio
 * Este arquivo é parte do programa SISICMBio
 * O SISICMBio é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro dos termos
 * da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão
 * 2 da Licença.
 *
 * Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem
 * uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
 * Licença Pública Geral GNU/GPL em português para maiores detalhes.
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENCA.txt",
 * junto com este programa, se não, acesse o Portal do Software Público Brasileiro no endereço
 * www.softwarepublico.gov.br ou escreva para a Fundação do Software Livre(FSF)
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA
 * */

use \br\gov\sial\core\mvcb\view\exception\ViewException,
    \br\gov\sial\core\valueObject\DataViewObject;

if (isset($_jsonData) && is_array($_jsonData)) {
    if (isset($_jsonData['result'])) {
        $result = array();

        foreach ($_jsonData['result'] as $value) {
            if ($value instanceof DataViewObject) {
                $result[] = $value->toArray();
            } else {
                $result[] = $value;
            }
        }

        $final = array(
            'result' => $result,
            'total'  => count($result),
            'status' => isset($_jsonData['status'])? $_jsonData['status'] : NULL
        );

        header('Cache-Control: no-cache, must-revalidate');
        header('Expires: Mon, 26 Jul 1997 05:00:00 GMT');
        header('Content-type: application/json');
        $json = json_encode($final);

        echo $json;
    } else {
        throw new ViewException('Informe o jsonData["result"]');
    }
} else {
    throw new ViewException('Informe o jsonData:array');
}
//@todo Identificar porque que está passando
//      informações adicionais para o output "<!DOC...".
//      Arrumar e remover o 'die'
die;
