<?php
/*
 * Copyright 2011 ICMBio
 * Este arquivo é parte do programa SISICMBio
 * O SISICMBio é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro dos termos
 * da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão
 * 2 da Licença.
 *
 * Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem
 * uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
 * Licença Pública Geral GNU/GPL em português para maiores detalhes.
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENCA.txt",
 * junto com este programa, se não, acesse o Portal do Software Público Brasileiro no endereço
 * www.softwarepublico.gov.br ou escreva para a Fundação do Software Livre(FSF)
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA
 * */
namespace br\gov\mainapp\application\libcorp\funcao\valueObject;
use br\gov\sial\core\valueObject\ValueObjectAbstract as ParentValueObject;

/**
  * SISICMBio
  *
  * Generated By SIAL Generator - vs 0.2.0
  *
  * @name FuncaoValueObject
  * @package br.gov.icmbio.sisicmbio.application.sica.Funcao
  * @subpackage valueObject
  * @schema(name="corporativo")
  * @entity(name="funcao")
  * @author Fabio Lima <fabioolima@gmail.com>
  * @author J. Augusto <augustowebd@gmail.com>
  * @version $Id$
  * @log(name="all")
  * */
class FuncaoValueObject extends ParentValueObject
{
    /**
     * @attr (
     *  name="sqFuncao",
     *  database="sq_funcao",
     *  primaryKey="TRUE",
     *  type="integer",
     *  nullable="FALSE",
     *  get="getSqFuncao",
     *  set="setSqFuncao"
     * )
     * */
     private $_sqFuncao;

    /**
     * @attr (
     *  name="noFuncao",
     *  database="no_funcao",
     *  type="string",
     *  nullable="FALSE",
     *  get="getNoFuncao",
     *  set="setNoFuncao"
     * )
     * */
     private $_noFuncao;

    /**
     * @param integer $sqFuncao
     * @param string $noFuncao
     * */
    public function __construct ($sqFuncao = NULL,
                                 $noFuncao = NULL)
    {
        parent::__construct();
        $this->setSqFuncao($sqFuncao)
             ->setNoFuncao($noFuncao)
             ;
    }

    /**
     * @return integer
     * */
    public function getSqFuncao ()
    {
        return $this->_sqFuncao;
    }

    /**
     * @return string
     * */
    public function getNoFuncao ()
    {
        return $this->_noFuncao;
    }

    /**
     * @param integer $sqFuncao
     * @return FuncaoValueObject
     * */
    public function setSqFuncao ($sqFuncao = NULL)
    {
        $this->_sqFuncao = $sqFuncao;
        return $this;
    }

    /**
     * @param string $noFuncao
     * @return FuncaoValueObject
     * */
    public function setNoFuncao ($noFuncao = NULL)
    {
        $this->_noFuncao = $noFuncao;
        return $this;
    }
}