<?php
    $view = $this;
    $acao = function($row) use ($view) {
        $sqTemaVinculado = '';
        switch ($row['tipo']) {
            case 'U':
                $sqTemaVinculado =  3;
                break;
            case 'E':
                $sqTemaVinculado =  1;
                break;
            case 'I':
                $sqTemaVinculado =  2;
                break;
            case 'C':
                $sqTemaVinculado =  0;
                break;
        }
    };
    $tipo = function($row) use ($view) {
        switch ($row['tipo']) {
            case 'U':
                return 'UNIDADE DE CONSERVAÇÃO';
            break;
            case 'E':
                return 'ESPÉCIES';
                break;
            case 'I':
                return 'EMPREENDIMENTO';
                break;
            case 'C':
                return 'CAVERNA';
                break;
        }
    };
    $configArray = array('columns'  => array(
                                  0 => array('column' => 'nome'),
                                  1 => array('column' => $tipo),
    ));

    $this->grid->setConfig($configArray);
    $data  = $this->grid->parseData($this->result);

    echo json_encode($data);