<?php
$view = $this;
$fnNuArtefato = function($row) {
    return $row['nuDigital']?:$row['nuArtefato'];
};
$fnDtVinculo = function($row) {
    return $row['dtVinculo']->toString('dd/MM/YYYY H:mm:s');
};
$configArray = array('columns' => array(
                        array('column' => 'noTipoArtefato'),
                        array('column' => $fnNuArtefato),
                        array('column' => $fnDtVinculo),
));

$this->grid->setConfig($configArray);
$data  = $this->grid->parseData($this->result);

echo json_encode($data);