<?php
/*
 * Copyright 2011 ICMBio
 * Este arquivo é parte do programa SISICMBio
 * O SISICMBio é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro dos termos
 * da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão
 * 2 da Licença.
 *
 * Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem
 * uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
 * Licença Pública Geral GNU/GPL em português para maiores detalhes.
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENCA.txt",
 * junto com este programa, se não, acesse o Portal do Software Público Brasileiro no endereço
 * www.softwarepublico.gov.br ou escreva para a Fundação do Software Livre(FSF)
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA
 * */
namespace br\gov\mainapp\application\libcorp\tipoDocumento\valueObject;
use br\gov\sial\core\valueObject\ValueObjectAbstract as ParentValueObject;

/**
  * SISICMBio
  *
  * Generated By SIAL Generator - vs 0.2.0
  *
  * @name TipoDocumentoValueObject
  * @package br.gov.icmbio.sisicmbio.application.libcorp.tipoDocumento
  * @subpackage valueObject
  * @schema(name="corporativo")
  * @entity(name="tipo_documento")
  * @author Fabio Lima <fabioolima@gmail.com>
  * @author J. Augusto <augustowebd@gmail.com>
  * @version $Id$
  * @log(name="all")
  * */
class TipoDocumentoValueObject extends ParentValueObject
{
    /**
     * @attr (
     *  name="noTipoDocumento",
     *  database="no_tipo_documento",
     *  type="string",
     *  nullable="FALSE",
     *  get="getNoTipoDocumento",
     *  set="setNoTipoDocumento"
     * )
     * */
     private $_noTipoDocumento;

    /**
     * @attr (
     *  name="sqTipoDocumento",
     *  database="sq_tipo_documento",
     *  primaryKey="TRUE",
     *  type="integer",
     *  nullable="FALSE",
     *  get="getSqTipoDocumento",
     *  set="setSqTipoDocumento"
     * )
     * */
     private $_sqTipoDocumento;

    /**
     * @param string $noTipoDocumento
     * @param integer $sqTipoDocumento
     * */
    public function __construct ($noTipoDocumento = NULL,
                                 $sqTipoDocumento = NULL)
    {
        parent::__construct();
        $this->setNoTipoDocumento($noTipoDocumento)
             ->setSqTipoDocumento($sqTipoDocumento)
             ;
    }

    /**
     * @return string
     * */
    public function getNoTipoDocumento ()
    {
        return $this->_noTipoDocumento;
    }

    /**
     * @return integer
     * */
    public function getSqTipoDocumento ()
    {
        return $this->_sqTipoDocumento;
    }

    /**
     * @param string $noTipoDocumento
     * @return br\gov\icmbio\sisicmbio\application\libcorp\tipoDocumento\valueObject\TipoDocumentoValueObject
     * */
    public function setNoTipoDocumento ($noTipoDocumento = NULL)
    {
        $this->_noTipoDocumento = $noTipoDocumento;
        return $this;
    }

    /**
     * @param integer $sqTipoDocumento
     * @return br\gov\icmbio\sisicmbio\application\libcorp\tipoDocumento\valueObject\TipoDocumentoValueObject
     * */
    public function setSqTipoDocumento ($sqTipoDocumento = NULL)
    {
        $this->_sqTipoDocumento = $sqTipoDocumento;
        return $this;
    }
}