<?php

$view = $this;

$mask = function($row) use ($view) {
            return '<div class="center">' . $view->maskNumber($row['sqCep'], 'cep') . '</div>';
        };

$acao = function($row) use ($view) {
            $codigo = array($row['sqEndereco'], $row['sqPessoa']);

            $button = $view->actionButton('Alterar', 'Endereco.alterar', $codigo, 'pencil')
                    . $view->actionButton('Excluir', 'Endereco.deletar', $codigo, 'trash');

            $button .= $view->formHidden('sqEndereco', $row['sqEndereco']);
            return $button;
        };

$numero = function($row) {
            return '<div class="center">' . $row['nuEndereco'] . '</div>';
        };

$configArray = array();
$configArray['columns'][0]['column'] = $mask;
$configArray['columns'][1]['column'] = 'noTipoEndereco';
$configArray['columns'][2]['column'] = 'txEndereco';
$configArray['columns'][3]['column'] = $numero;
$configArray['columns'][4]['column'] = 'noBairro';
$configArray['columns'][5]['column'] = 'noEstado';
$configArray['columns'][6]['column'] = 'noMunicipio';
$configArray['columns'][7]['column'] = $acao;


$this->grid->setConfig($configArray);
$data = $this->grid->parseData($this->result);

echo json_encode($data);